In [48]:
import numpy as np
import pandas as pd

In [49]:
x = np.array([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape(2, 3)
print('reashape x:\n', x_reshape)

beginning x:
 [1 2 3 4 5 6]
reashape x:
 [[1 2 3]
 [4 5 6]]


In [50]:
x = np.random.normal(size=50)
x

array([-1.65942963,  0.87887884, -1.68409741,  0.34706855, -2.2318443 ,
       -0.51933748,  0.24791346, -0.81964362, -0.08305367, -0.7730214 ,
       -0.21618135, -0.10190456,  0.6651643 , -1.17881991, -0.03147713,
       -1.02385682,  0.56375894, -0.22564385, -0.22824122,  0.19007647,
        0.23659764,  1.74098449,  0.1531566 , -0.23535525,  0.5753887 ,
       -0.97573797, -0.0735702 , -1.89130102,  1.46037359,  0.4285224 ,
        1.20282667,  0.31289477, -0.47969374, -0.14820135, -0.55895302,
        0.07131604, -0.25686379, -0.86338074,  0.26807031, -0.90054451,
       -0.33343497, -1.06913756, -1.66972473, -0.51260105, -0.44740665,
        0.46510579, -0.66235528, -1.05131318,  0.09934896,  0.74700609])

In [51]:
y = x + np.random.normal(loc = 50, scale = 1, size = 50)

In [52]:
np.corrcoef(x, y)

array([[1.        , 0.73919396],
       [0.73919396, 1.        ]])

In [67]:
rng = np.random.default_rng(42)

In [82]:
rng.normal(size=(10, 1)).mean(axis=0)

array([0.35639078])